<template>
    <div>
        <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><h2 class="h4 mb-0">Activos</h2><button class="btn btn-brand" @click="openCreate"><FontAwesomeIcon icon="fa-solid fa-plus" class="me-2" />Nuevo activo</button></div>
        <div v-if="loading" class="text-center py-5 text-muted">Cargando activos...</div>
        <div v-else class="card border-0 shadow-sm">
            <div class="p-3 d-flex flex-wrap gap-2 align-items-center"><select v-model="statusFilter" class="form-select form-select-sm w-auto"><option value="todos">Todos</option><option value="activo">Activos</option><option value="inactivo">Desactivados</option></select><input v-model.trim="search" class="form-control form-control-sm" style="max-width:280px" placeholder="Buscar código, nombre o categoría"></div>
            <div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="thead-brand"><tr><th>Código</th><th>Nombre</th><th>Categoría</th><th>Ubicación</th><th>Estado</th><th>Costo</th><th>Registro</th><th></th></tr></thead><tbody><tr v-if="!paginatedActivos.length"><td colspan="8" class="text-center text-muted py-4">Sin activos registrados.</td></tr><tr v-for="activo in paginatedActivos" :key="activo.id"><td class="fw-semibold">{{ activo.codigo }}</td><td>{{ activo.nombre }}<small v-if="activo.numero_serie" class="d-block text-muted">Serie: {{ activo.numero_serie }}</small></td><td>{{ activo.categoria }}</td><td>{{ activo.ubicacion || '—' }}</td><td><span class="badge" :class="activo.activo ? 'text-bg-success' : 'text-bg-secondary'">{{ activo.activo ? stateLabel(activo.estado) : 'Desactivado' }}</span></td><td>Q {{ money(activo.costo_compra) }}</td><td class="small">{{ date(activo.created_at) }}</td><td><div class="d-flex gap-1"><button class="btn btn-sm btn-action-brand" title="Editar" @click="openEdit(activo)"><FontAwesomeIcon icon="fa-solid fa-pencil" /></button><button class="btn btn-sm btn-action-brand" :title="activo.activo ? 'Desactivar' : 'Activar'" @click="openToggle(activo)"><FontAwesomeIcon :icon="activo.activo ? 'fa-solid fa-ban' : 'fa-solid fa-check'" /></button></div></td></tr></tbody></table></div>
            <TablePagination v-model:page="page" v-model:perPage="perPage" :total-items="filteredActivos.length" />
        </div>

        <div ref="formModalRef" class="modal fade" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header modal-header-brand"><h5 class="modal-title">{{ editingId ? 'Editar activo' : 'Nuevo activo' }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal" /></div><form @submit.prevent="save"><div class="modal-body row g-3"><div v-if="errors.length" class="col-12"><div class="alert alert-danger mb-0"><ul class="mb-0 ps-3"><li v-for="error in errors" :key="error">{{ error }}</li></ul></div></div><div class="col-md-4"><label class="form-label">Código *</label><input v-model="form.codigo" class="form-control" maxlength="50" required></div><div class="col-md-8"><label class="form-label">Nombre *</label><input v-model="form.nombre" class="form-control" maxlength="150" required></div><div class="col-md-6"><label class="form-label">Categoría *</label><input v-model="form.categoria" class="form-control" placeholder="Ej. Refrigeración" maxlength="100" required></div><div class="col-md-6"><label class="form-label">Ubicación</label><input v-model="form.ubicacion" class="form-control" placeholder="Ej. Tienda" maxlength="150"></div><div class="col-md-4"><label class="form-label">Marca</label><input v-model="form.marca" class="form-control" maxlength="100"></div><div class="col-md-4"><label class="form-label">Modelo</label><input v-model="form.modelo" class="form-control" maxlength="100"></div><div class="col-md-4"><label class="form-label">Número de serie</label><input v-model="form.numero_serie" class="form-control" maxlength="100"></div><div class="col-md-4"><label class="form-label">Fecha de compra</label><input v-model="form.fecha_compra" class="form-control" type="date"></div><div class="col-md-4"><label class="form-label">Costo de compra</label><input v-model.number="form.costo_compra" class="form-control" type="number" min="0" step="0.01"></div><div class="col-md-4"><label class="form-label">Estado *</label><select v-model="form.estado" class="form-select"><option value="activo">Activo</option><option value="mantenimiento">Mantenimiento</option><option value="danado">Dañado</option><option value="baja">Baja</option></select></div><div class="col-12"><label class="form-label">Descripción</label><textarea v-model="form.descripcion" class="form-control" rows="2" maxlength="2000" /></div><div class="col-12 form-check form-switch ms-2"><input id="activo-habilitado" v-model="form.activo" class="form-check-input" type="checkbox"><label class="form-check-label" for="activo-habilitado">Activo en el sistema</label></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-brand" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-brand" :disabled="saving">{{ saving ? 'Guardando...' : 'Guardar' }}</button></div></form></div></div></div>
        <ModalConfirm ref="confirmModalRef" :title="selected?.activo ? 'Desactivar activo' : 'Activar activo'" :message="`¿Desea ${selected?.activo ? 'desactivar' : 'activar'} el activo <strong>${selected?.nombre || ''}</strong>?`" confirm-text="Confirmar" :loading="toggling" @confirm="toggle" />
    </div>
</template>

<script setup>
import { Modal } from 'bootstrap';
import { computed, onMounted, ref } from 'vue';
import axios from '@/bootstrap';
import ModalConfirm from '@/components/components_ui/ModalConfirm.vue';
import TablePagination from '@/components/components_ui/TablePagination.vue';
import { formatMoney } from '@/utils/formatters';

const activos = ref([]); const loading = ref(true); const saving = ref(false); const toggling = ref(false); const editingId = ref(null); const selected = ref(null); const errors = ref([]); const statusFilter = ref('todos'); const search = ref(''); const page = ref(1); const perPage = ref(10); const formModalRef = ref(null); const confirmModalRef = ref(null); let formModal = null;
const emptyForm = () => ({ codigo: '', nombre: '', categoria: '', ubicacion: '', marca: '', modelo: '', numero_serie: '', fecha_compra: '', costo_compra: null, estado: 'activo', descripcion: '', activo: true }); const form = ref(emptyForm());
const filteredActivos = computed(() => activos.value.filter((item) => (statusFilter.value === 'todos' || (statusFilter.value === 'activo') === Boolean(item.activo)) && `${item.codigo} ${item.nombre} ${item.categoria}`.toLowerCase().includes(search.value.toLowerCase())).sort((a, b) => new Date(b.created_at) - new Date(a.created_at)));
const paginatedActivos = computed(() => filteredActivos.value.slice((page.value - 1) * perPage.value, page.value * perPage.value));
onMounted(async () => { formModal = new Modal(formModalRef.value); await load(); });
function money(value) { return formatMoney(value || 0); } function date(value) { return value ? new Date(value).toLocaleDateString('es-GT') : '—'; } function stateLabel(value) { return ({ activo: 'Activo', mantenimiento: 'Mantenimiento', danado: 'Dañado', baja: 'Baja' })[value] || value; }
async function load() { loading.value = true; try { const { data } = await axios.get('/activos/get'); activos.value = data.data ?? []; } finally { loading.value = false; } }
function openCreate() { editingId.value = null; form.value = emptyForm(); errors.value = []; formModal.show(); }
function openEdit(item) { editingId.value = item.id; form.value = { ...emptyForm(), ...item, fecha_compra: item.fecha_compra ? String(item.fecha_compra).slice(0, 10) : '' }; errors.value = []; formModal.show(); }
function openToggle(item) { selected.value = item; confirmModalRef.value?.open(); }
async function save() { saving.value = true; errors.value = []; try { const request = editingId.value ? axios.put(`/activos/update/${editingId.value}`, form.value) : axios.post('/activos/store', form.value); const { data } = await request; const index = activos.value.findIndex((item) => item.id === data.data.id); if (index >= 0) activos.value[index] = data.data; else activos.value.unshift(data.data); formModal.hide(); } catch (error) { errors.value = error.response?.data?.errors ? Object.values(error.response.data.errors).flat() : [error.response?.data?.message || 'No se pudo guardar.']; } finally { saving.value = false; } }
async function toggle() { toggling.value = true; try { const { data } = await axios.patch(`/activos/toggle/${selected.value.id}`); const index = activos.value.findIndex((item) => item.id === selected.value.id); if (index >= 0) activos.value[index] = data.data; confirmModalRef.value?.close(); } finally { toggling.value = false; } }
</script>
